### ISSUE TITLE
Unsure how to specify script as query_command

### ISSUE THREAD

**Issue by michK** [qsuscs/mutt-addressbook#3]
Good day,

I am not quite sure how to specify this script as the query_command for mutt. I am not used to configuring .ini files (I believe this is a Windows thing?).

I believe query_command should be set in a file that is sourced by mutt as `query_command = some_script`, but in this case I'm not sure if I should install this package or just set it as `query_command = mutt-addressbook.py`?

Thanks in advance
Michael

**Comment by qsuscs** [comment]
You can specify `query_command = mutt-addressbook.py` if the config for it is in one of the expected locations, or e.g. `query_command = mutt-addressbook.py -C ~/.mutt/mutt-addressbook.ini` if you have it in a non-standard location.

**Comment by michK** [comment]
Thanks, appreciate it!

Michael
